### PR TITLE
IsValid is slow

### PR DESCRIPTION
**Pull request by kalis0x**
just checking if it's nil or null does the same thing :v

-edit-
tested it just to be sure, i was correct:
] lua_openscript_cl test.lua
Running script test.lua...
IsValid: 3.7235004128888e-006
Regular Check: 2.4823599687807e-005
] lua_openscript_cl test.lua
Running script test.lua...
IsValid: 4.0339000406675e-006
Regular Check: 2.5754399757716e-005
] lua_openscript_cl test.lua
Running script test.lua...
IsValid: 3.41320037478e-006
Regular Check: 2.5133899725915e-005
] lua_openscript_cl test.lua
Running script test.lua...
IsValid: 4.0337999962503e-006
Regular Check: 3.2891200135055e-005
] lua_openscript_cl test.lua
Running script test.lua...
IsValid: 3.7234999581415e-006
Regular Check: 2.5444200218772e-005

### CODE REVIEW

**Comment by Kefta** [comment]
That's because it also checks Entity:IsValid, which is necessary for engine entities. The nil check is not really necessary in most cases, however, it's extremely negligible and won't affect your speed at all.

**Comment by Kefta** [comment]
Also, from your tests, it looks like IsValid is still faster? e*-6 vs e*-5? Or am I reading your results incorrectly?

**Comment by kalis0x** [comment]
something was acting up, restarted gmod and did another test
] lua_openscript_cl test.lua
Running script test.lua...
IsValid: 2.482356649125e-006
Regular Check: 3.1650047290555e-005

0.0042738072377038
vs.
0.0031486775212081

it's so miniscule that it doesn't really make a difference and apparently what you said about engine ents is true, so i guess it's not good to do this and instead use IsValid

**Comment by zerfgog** [comment]
:-1:

**Comment by kalis0x** [comment]
:+1:

**Pull request closed without merging**
